# Generated by Django 5.1.6 on 2025-03-15 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvestmentInquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=50, null=True)),
                ('investment_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('investment_goal', models.CharField(max_length=255)),
                ('risk_tolerance', models.CharField(blank=True, max_length=50, null=True)),
                ('sectors', models.CharField(blank=True, max_length=255, null=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
