# Generated by Django 5.1.6 on 2025-03-17 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_startup'),
    ]

    operations = [
        migrations.AddField(
            model_name='startup',
            name='founder_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='startup',
            name='industry',
            field=models.CharField(choices=[('technology', 'Technology'), ('healthcare', 'Healthcare'), ('fintech', 'Fintech'), ('education', 'Education'), ('ecommerce', 'E-commerce'), ('other', 'Other')], default='other', max_length=50),
        ),
        migrations.AddField(
            model_name='startup',
            name='startup_stage',
            field=models.CharField(choices=[('idea', 'Idea Stage'), ('mvp', 'MVP'), ('early', 'Early Traction'), ('growth', 'Growth Stage'), ('scaling', 'Scaling')], default='idea', max_length=50),
        ),
    ]
