# Generated by Django 5.1.6 on 2025-03-17 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_startup_founder_name_startup_industry_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='startup',
            name='phone',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
